[Documentation] Added package-info documentation for (most) packages
fastjengine/FastJ pull request #112
Opened 2021-08-19 14:34 UTC by YeffyCodeGit

# PR Title

## Additions
- Added package-info files for most, if not all package

## Notes
- I didn't write all the package-info files, because I couldn't properly understand some of the packages. If you could provide some insight on what those packages do, and /or some ideas for what to write, that would be great! :D

2021-09-14 16:59 UTC, lucasstarsz requested changes
Thanks for contributing to FastJ -- we're happy to have you!
Unfortunately, these will not work as package comments for a few reasons outlined below:

1. The style of writing overall needs improvement -- rather than try to over-explain what a package is and does, you can simply write what the package is about. Unless more clarification is needed, this is all that would be required of a `package-info` file. An example of this is provided in the comment made on `tech.fastj.engine.internals`.

Furthermore, none of these are documentation comments. A documentation comment consists of **2** asterisks (\*) after the forward slash, like so:

```java
/**
 * content
 */
```
or:
```java
/** content */
```

As for not knowing what some of these packages do, that's perfectly fine! Just focus on the packages which you actually understand the purpose of -- other people can take care of the rest.

2021-09-15 06:23 UTC, YeffyCodeGit commented on src/main/java/tech/fastj/engine/internals/package-info.java
> + */
Hey! Thanks for the pointers, i'll update it and commit again by today!

2021-09-16 15:51 UTC, YeffyCodeGit commented
Fixed!

2021-09-16 20:30 UTC, lucasstarsz requested changes
Not bad -- a few more changes to be made. I will say though, I would rather you remove the empty package info files. There's no point in having them if they're empty, which is what I was implying in the last review.

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/systems/fio/package-info.java
> + * Code which provides simple methods to work with files.
Replace "code which provides" with "system providing".

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/systems/behaviors/package-info.java
> + * Code for the FastJ behaviour system.
Consider: "API for FastJ's behavior system."

> behaviour

Furthermore, please use American-style wording for any documentation/code in FastJ.

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/systems/audio/package-info.java
> + * The FastJ audio system.
Consider: "FastJ's audio system".

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/math/package-info.java
> + * Math helpers meant to be used in FastJ Games.
Consider: "FastJ's math library".

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/input/package-info.java
> + * Handles all input events in FastJ.
To keep consistent with (most of) your other package info messages, remove "in FastJ".

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/graphics/ui/package-info.java
> + * All the code for UI in FastJ.
Consider a more to-the-point statement: "FastJ's UI system".

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/graphics/package-info.java
> +  Everything related to graphics and rendering in FastJ.
Consider: "FastJ's Graphics and Rendering system".

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/graphics/io/package-info.java
> + * Code to read models and other data from files into FastJ.
Consider: "FastJ model file IO".

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/graphics/game/package-info.java
> + * Different elements meant to be used in a FastJ game.
This is a bit too broad of a topic -- "different elements" what elements? We can't tell anything about these elements other than that they should be used in a FastJ game, and _quite literally anything_ in FastJ's source could or maybe even should be used in a FastJ game.

Consider a more focused approach: "{\@code GameObject}s and specific instances".

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/graphics/display/package-info.java
> + * C
This seems incomplete -- it should be removed alongside the other empty package infos.

2021-09-16 20:30 UTC, lucasstarsz commented on src/main/java/tech/fastj/engine/package-info.java
> + * Classes used internally inside FastJ.
> internally inside

This is fairly redundant -- internal and inside both mean the same thing in this context.
Consider: "FastJ's internal engine classes".

2021-09-19 16:05 UTC, lucasstarsz approved these changes
Looks good. Thanks for contributing to FastJ!

2021-09-19 16:06 UTC, merged