Update engine logging instances
fastjengine/FastJ pull request #169
Opened 2022-01-06 22:12 UTC by YeffyCodeGit

# PR Title

## Bug Fixes

Update all the uses of logging functions to use formatted strings instead of string concatenation

2022-01-06 22:41 UTC, lucasstarsz requested changes
Thanks for making a PR to FastJ! It's always very appreciated 👍🏾 
Things are looking good so far, but there are a few changes I'd like you to make. Please review my comments below.

2022-01-06 22:41 UTC, lucasstarsz commented on src/main/java/tech/fastj/engine/FastJEngine.java
> +                FastJEngine.warning("Interrupted while syncing game frame rate: {}" + exception.getMessage() + Arrays.deepToString(exception.getStackTrace()));
Seems like you've added the {} formatting, but the string concatenation is still present.

2022-01-06 22:41 UTC, lucasstarsz commented on examples/java/tech/fastj/examples/bullethell/scripts/BulletMovement.java
> +            FastJEngine.warning("not moving! bullet at {} with {} f {}", originalTranslation, travelAngle, travelVector);
There shouldn't be a space between the brackets and the `f`.

2022-01-06 22:41 UTC, lucasstarsz commented on examples/java/tech/fastj/examples/bullethell/scripts/BulletMovement.java
> +            FastJEngine.log("death! of bullet {} f {}", travelAngle, travelVector);
As mentuoned above, there's an extra space between the first brackets and the `f`.

2022-01-06 22:41 UTC, lucasstarsz commented on src/main/java/tech/fastj/engine/internals/ThreadFixer.java
> +                        FastJEngine.warning("Interrupted while in daemon sleep: {}" + exception.getMessage() + Arrays.deepToString(exception.getStackTrace()));
Seems like you've added the {} formatting, but the string concatenation is still present here.

2022-01-06 22:41 UTC, lucasstarsz commented on src/main/java/tech/fastj/systems/audio/MemoryAudioPlayer.java
>              return;
Just an extra space before `but` that needs to be deleted.

2022-01-06 23:00 UTC, YeffyCodeGit commented
Thanks for the review, i'll fix the mentioned issues in a bit! 👍

2022-01-07 14:42 UTC, YeffyCodeGit commented
Sorry, I didn't notice I had missing changes, but it should all be done now.

2022-01-08 23:11 UTC, lucasstarsz approved these changes
Looks good. Don't worry about that failed unit test -- that's to be fixed separately.

2022-01-08 23:12 UTC, merged